### ISSUE TITLE
Makefile detection

### ISSUE THREAD

**Issue by Jippeheijnen** [Niels-Post/HCT#2]
Makefile detection fails when relative makefile in source directory points to hwlib makefile.

**Comment by Niels-Post** [comment]
Since there are many Makefiles in HWLib and HWLIB projects, it is impractical to include every single makefile automatically.
Therefore, makefiles are automatically loaded when they satisfy all conditions:
- Are called "Makefile" (no extension) 
- Contain a direct include of either "$(HWLIB)/Makefile" or  "$(RELATIVE)/Makefile"

In build systems where Makefiles do not have one of these, the phrase "#HCTMarker" can be placed in the makefile to have HCT automatically include it.

Alternatively, the makefile can be loaded to HCT by calling the hct_add function directly:
HCT_ADD(<<TARGET_NAME>> <<TARGET_ROOT_DIR>> <<TARGET_MAKEFILE_NAME>>)

TARGET_NAME: The name of the target HCT creates
TARGET_ROOT_DIR: Full path to the directory the makefile is in
TARGET_MAKEFILE_NAME: Name of the Makefile (i.e. in case it has an extension)
